filter:
    excluded_paths: [build/*, config/*, data/*, public/*, scss/*, vendor/*]

before_commands:
    - 'composer install --dev --prefer-source --no-interaction'

tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["module/*"]
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [config, data, public, scss, vendor]
    php_cpd:
        enabled: true
        excluded_dirs: [config, data, public, scss, vendor]

checks:
    php:
        code_rating: true
        duplication: true
