language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - composer validate --strict
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit
