language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  include:
    - php: 5.6
      env: 'UPLOAD_COVERAGE=true'
  fast_finish: true

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - composer validate --strict
  - vendor/bin/phpcs --standard=ruleset.xml
  - vendor/bin/phpunit

after_script:
  - if [[ $UPLOAD_COVERAGE == 'true' ]]; then ./vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml ;

notifications:
  email: false
  irc: "irc.freenode.org#zource"
